### ISSUE TITLE
Curses dont spawn, if there is a way to spawn them tell me

### ISSUE THREAD

**Issue by Baddexbaird** [RadonCoding/jujutsu-kaisen#27]
Havent seen a single curse spawn naturally, there used to be casing for cursed items to go into that made them spawn but it was removed

**Comment by Baddexbaird** [comment]
also, is there a discord?

**Comment by RadonCoding** [comment]
curses spawn but they rarely become visible unless you place a veil, higher grade curses are always visible

**Comment by RadonCoding** [comment]
there is no discord server because the development is temporarily on pause etc (im busy)

**Comment by Baddexbaird** [comment]
cool, thank you ❤️
